In [48]:
import numpy as np
import math
import matplotlib.pyplot as plt


In [6]:
def sigmoide(x):
  if x < -5:
    return 0
  elif x > 5:
    return 1
  else:
    return 1/(1+math.exp(-x))

In [7]:
sigmoide_vec = np.vectorize(sigmoide)

In [41]:
def neurona(ent,pesos,bias):
  entrada_neta = np.dot(pesos,ent)+bias
  salida = sigmoide_vec(entrada_neta)

  return salida[0]

In [42]:
def perceptron(entradas,salidas,factor_aprendizaje,max_iter):
  pesos = 2*np.random.rand(1,entradas.shape[1])-1
  bias = 2*np.random.rand(1)-1
  historico = []
  for it in range(0,max_iter):
    cant_errores = 0
    error_it = 0
    for ent,sal_deseada in zip(entradas,salidas):
      salida_obtenida = neurona(ent,pesos,bias)
      error = sal_deseada - salida_obtenida    
      error_it += abs(error)
      if error != 0:
        cant_errores +=1
        pesos = pesos + factor_aprendizaje*error*ent
        bias = bias+factor_aprendizaje*error*(1)

    historico.append(error_it)
    if cant_errores==0:
      break


  return pesos,bias,historico

In [43]:
entradas = np.array([[1,1],[1,0],[0,1],[0,0]])
salidas = np.array([ [ (x[0] and x[1]) , (x[0] or x[1]) ] for x in entradas])

In [44]:
#Primera neurona

pesosN1,biasN1,historiaN1 = perceptron(entradas,salidas[:,0],0.9,1000)
print(pesosN1,biasN1)

for ent,sal in zip(entradas,salidas[:,0]):
  print("Entrada ",ent," Salida esperada ",sal," Salida obtenida ",neurona(ent,pesosN1,biasN1))

[[10.00385466 10.01125216]] [-15.01336509]
Entrada  [1 1]  Salida esperada  1  Salida obtenida  1
Entrada  [1 0]  Salida esperada  0  Salida obtenida  0
Entrada  [0 1]  Salida esperada  0  Salida obtenida  0
Entrada  [0 0]  Salida esperada  0  Salida obtenida  0


In [47]:
#Segunda neurona

pesosN2,biasN2,historiaN2 = perceptron(entradas,salidas[:,1],0.9,1000)
print(pesosN2,biasN2)

for ent,sal in zip(entradas,salidas[:,1]):
  print("Entrada ",ent," Salida esperada ",sal," Salida obtenida ",neurona(ent,pesosN2,biasN2))

[[10.00420844 10.00461202]] [-5.0006173]
Entrada  [1 1]  Salida esperada  1  Salida obtenida  1
Entrada  [1 0]  Salida esperada  1  Salida obtenida  1
Entrada  [0 1]  Salida esperada  1  Salida obtenida  1
Entrada  [0 0]  Salida esperada  0  Salida obtenida  0


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])